// game
// designer
// system
// todays date
// game genre
// pic/video/review/tutorial/ walkthrough
// agreement to take down check box
// content uploader ip
// content uploader id this will be the csbr DB id number which will be mongo and sql id's that are autogenerated
// content uploader csbr_name
// gamer tag for content
// tip jar
// dig and bury
// #tag for the contents selecting or making as many tags as wanted (this will help categorize content and build it into the search engine)

import react from "React";
import PropTypes from "prop-types";
const UGC_Upload = (children, onsubmit) => {
    return (
        <form onSubmit={onsubmit}
            style={{
                display: "contents",
                gridColumn: "1/-1",
                gridRow: "1/-1",
            }}>
            
            {children}

            </form>
    )}
    

UGC_Upload.PropTypes = {
    children: PropTypes.node,
    onsubmit: PropTypes.func,
}
//SCHEMA and fields needed for the upload form
//This will be used for designing the upload form for all UGC content
// also will be used for search and filtering of content
// this schema should be used for the inital upload
// game

// designer
// system
// todays date
// game genre
// description of content
// pic/video/tutorial/ walkthrough
// agreement to take down check box
// content uploader ip
// content uploader id this will be the csbr DB id number which will be mongo and sql id's that are autogenerated
// content uploader csbr_name
// gamer tag for content
// tip jar
// dig and bury
// #tag for the contents selecting or making as many tags as wanted (this will help categorize content and build it into the search engine)